<div class="container-fluid browse-post">
    <div class="page-header">
        <h4 class="title-header">Bài chờ duyệt</h4>
        

  <!-- Modal -->
  
        <div class="dropdown">
            <button type="button" class="btn btn-primary button-filter" data-toggle="modal" data-target="#staticBackdrop">
                Bộ lọc
            </button>
            <!-- Modal -->
            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Lọc theo Tag</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>
                        <button href="#" class="btn btn-primary choose">CSS</button>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Sắp xếp
            </button>

            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Cũ nhất</a>
                <a class="dropdown-item" href="#">Mới nhất</a>

            </div>
        </div>
    </div>

    <div class="wrapper">
        <div class="card bpost-card">
            <div class="card-header">
                <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                <span>Nguyen Minh Quang</span>
            </div>
            <div class="card-body">
                <p class="title-text">what is css?</p>

                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!</p>
                <button href="#" class="btn btn-primary stretched-link">CSS</button>
                <button href="#" class="btn btn-primary stretched-link">PHP</button>

            </div>
            <div class="card-footer button-browse ">
                <button type="button" class="btn btn-primary">Duyệt</button>
                <button type="button" class="btn btn-danger">Hủy</button>
            </div>
        </div>
        <div class="card bpost-card">
            <div class="card-header">
                <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                <span>Nguyen Minh Quang</span>
            </div>
            <div class="card-body">
                <p class="title-text">what is css?</p>
                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!</p>
                <button href="#" class="btn btn-primary stretched-link">CSS</button>
                <button href="#" class="btn btn-primary stretched-link">PHP</button>
            </div>
            <div class="card-footer button-browse ">
                <button type="button" class="btn btn-primary">Duyệt</button>
                <button type="button" class="btn btn-danger">Hủy</button>
            </div>
        </div>
        <div class="card bpost-card">
            <div class="card-header">
                <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                <span>Nguyen Minh Quang</span>
            </div>
            <div class="card-body">
                <p class="title-text">what is css?</p>
                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!</p>
                <button href="#" class="btn btn-primary stretched-link">CSS</button>
                <button href="#" class="btn btn-primary stretched-link">PHP</button>
            </div>
            <div class="card-footer button-browse ">
                <button type="button" class="btn btn-primary">Duyệt</button>
                <button type="button" class="btn btn-danger">Hủy</button>
            </div>
        </div>


    </div>



</div>