<div class="container-fluid browse-post">
    <div class="page-header">
        <h4 class="title-header">Bài chờ duyệt</h4>


        <!-- Modal -->

        <div class="dropdown">

            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="modal" data-target="#staticBackdrop">
                Bộ lọc
            </button>
            <!-- Modal -->
            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Lọc theo Tag</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>
                            <button href="#" class="btn btn-primary choose">CSS</button>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Sắp xếp
            </button>

            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Cũ nhất</a>
                <a class="dropdown-item" href="#">Mới nhất</a>

            </div>
        </div>
    </div>

    <div class="wrapper">


       <? if (count($data)==0): ?>
       
        <?
        else :
        ?>
        
            <?php
        foreach ($data as $item => $value) {


        ?><div class="card bpost-card">
                <div class="card-header">
                    <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                    <span>Nguyen Minh Quang</span>
                </div>
                <div class="card-body">
                    <p class="title-text"><?php echo $value["forum_name"] ?></p>
                    <p class="card-text"><?php echo $value["forum_content"]?></p>
                    
                </div>
                <div class="card-footer button-browse ">
                    <form>
                    <button type="submit" class="btn btn-primary" name="action" value="legalize">Duyệt</button>
                    <input type="hidden" name="forum-id" value=<?php echo $value["forum_id"]; ?> />
                    </form>
                    <button type="button" class="btn btn-danger">Hủy</button>
                </div>
            </div>
        <?php
        } 
        ?>
       <? endif; ?>


    </div>



</div>


<!-- Modal Delete -->
<div class="modal fade" id="DeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Không duyệt bài viết</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Xác nhận không duyệt bài viết này?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                <button type="button" class="btn btn-primary">Không duyệt</button>
            </div>
        </div>
    </div>
</div>