<div class="container-fluid emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="/view/img_avatar2.png" alt="Card image cap" />

                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        <?php echo $lastname ?>  <?php echo $firstname ?> 
                    </h5>
                  
                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Câu hỏi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Comment</a>
                        </li>
                    </ul>
                </div>
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>Email:</p>
                    <a href=""><?php echo $email ?></a><br />
                    <p>Tài khoản:</p>
                    <a href=""><?php echo $username ?></a><br />
                    <p>Số lượng câu hỏi đã hỏi</p>
                    <a href="">12</a><br />
                    
                    <p>Số lượng câu trả lời</p>
                    <a href="">12</a><br />
                    <p>Số lượng bị report</p>
                    <a href="">12</a><br />
                   
                </div>
            </div>
            <div class="col-md-8">

                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Experience</label>
                            </div>
                            <div class="col-md-6">
                                <p>Expert</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Hourly Rate</label>
                            </div>
                            <div class="col-md-6">
                                <p>10$/hr</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Total Projects</label>
                            </div>
                            <div class="col-md-6">
                                <p>230</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>English Level</label>
                            </div>
                            <div class="col-md-6">
                                <p>Expert</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Availability</label>
                            </div>
                            <div class="col-md-6">
                                <p>6 months</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label>Your Bio</label><br />
                                <p>Your detail description</p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <?php foreach($comments as $it =>$item  ) {?>
                            <div class="row">
                            <div class="card post-card">
                                <form>
                                    <div class="card-header">
                                        <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                                        <span>Nguyen Minh Quang</span>

                                    </div>
                                    <div class="card-body body-post">
                                        <div class="answer">
                                            <p class="card-text">Answer</p>
                                            <p class="card-text">1</p>
                                        </div>
                                        <div class="answer">
                                            <p class="card-text">Like</p>
                                            <p class="card-text">1</p>
                                        </div>
                                        <div class="post-detail">
                                            <p class="title-text">asdasd</p>
                                            <button type="button" class="btn btn-primary btn-sm">CSS</button>
                                            <button type="button" class="btn btn-primary btn-sm">HTML</button>
                                            <button type="button" class="btn btn-primary btn-sm">PHP</button>
                                        </div>

                                    </div>
                                    </from>

                                    <div class="card-footer button-browse ">
                                        <form action="<?php echo 'index.php?action=detail'; ?>">

                                            <button type="submit" class="btn btn-primary ahr">Xem chi tiết</button>

                                            <input type="hidden" name="id" value=<?php echo $item["forum_id"]; ?> />
                                            <input type="hidden" name="userID" value=<?php echo $item["user_id_fk"]; ?> />
                                            <input type="hidden" name="forum_content" value=<?php echo $item["forum_content"]; ?> />
                                            <input type="hidden" name="forum_name" value=<?php echo $item["forum_name"] ?> />
                                            <input type="hidden" name="id-post" value=<?php echo $item["forum_id"] ?> />
                                            <input type="hidden" name="action" value="detail" />


                                        </form>
                                    </div>


                            </div>
                        </div>

                        <?php }?>
                        



                    </div>

                </div>
            </div>
        </div>
    </form>
</div>