<div class="container-fluid">
    <div class="wrapper">
        <div class="card post-card">
            <div class="card-header card-detail">
                <div class="user-info">
                    <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                    <span>Nguyen Minh Quang</span>
                </div>
                <div class="status-info">
                   <button type="submit" class="btn btn-danger ban-button" name="action" value="delete-forum">Xóa bài viết</button>
                    <input type="hidden" name="id-post" value="<?php echo $id?>"/>
                    <input type="hidden" name="user-id-post" value="<?php echo $userID?>"/>
                    <button class="like-btn">1 Likes</button>
                    <button class="report-btn">1 Reports</button>

                </div>
            </div>
            <div class="card-body">

                <p class="title-text"><?php echo  $forum_name ?></p>
                <p class="card-text"><?php echo $content ?></p>
                <button class="btn btn-primary">CSS</button>
                <button class="btn btn-primary ">PHP</button>

            </div>
            <div class="card-footer button-browse ">
                <!-- <div class="comment-user">
                <div class="image-user">
                  <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                  
                </div>
                <div class="comment-form">
                <textarea placeholder="Write your comment here!" class="pb-cmnt-textarea"></textarea>
                </div>
                </div> -->
                <?php
                foreach ($comments as $item =>$value) {


                ?>
                    <div class="comment">
                        <div class="comment-info">
                            <div class="image-user">
                                <img class="avatar-comment" src="/view/img_avatar2.png" alt="Card image cap">
                            </div>
                            <div class="comment-text">
                            <?php echo $value["commentContent"] ?>
                            </div>
                            <div class="comment-status">
                                
                                <form>
                                <button type="submit" class="button-delete ">Xóa comment</button>
                                <input type="hidden" name="id-post" value="<?php echo $id?>"/>
                                <input type="hidden" name="user-id-post" value="<?php echo $userID?>"/>
                                <input type="hidden" name="id-comment" value="<?php echo $value["commentId"]?>"/>
                                <input type="hidden" name="action" value="delete-comment"/>
                </form>
                               

                                <div class="a">
                                    <div class="buttonlikecontainer"><button class="like-btn"><?php echo $value["num_of_likes"]?> Likes</button></div>

                                </div>
                            </div>
                        </div>

                    </div>
                <?php
                }
                ?>



            </div>
        </div>


    </div>

</div>
</div>