<div class="container-fluid">
    <div class="wrapper">
        <div class="card post-card">
        <div class="card-header card-detail">
                <div class="user-info">
                <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                <span>Nguyen Minh Quang</span>
                </div>
                <div class="status-info">
                <button class="delete-btn">Xóa bài viết</button>
                <button class="like-btn">1 Likes</button>
                <button class="report-btn">1 Reports</button>
 
                </div>
            </div>
            <div class="card-body">
                <p class="title-text">what is css?</p>

                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!</p>
                <button  class="btn btn-primary">CSS</button>
                <button class="btn btn-primary ">PHP</button>

            </div>
            <div class="card-footer button-browse ">
                <!-- <div class="comment-user">
                <div class="image-user">
                  <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                  
                </div>
                <div class="comment-form">
                <textarea placeholder="Write your comment here!" class="pb-cmnt-textarea"></textarea>
                </div>
                </div> -->
                <div class="comment">
                    <div class="comment-info">
                    <div class="image-user">
                        <img class="avatar-comment" src="/view/img_avatar2.png" alt="Card image cap">
                    </div>
                    <div class="comment-text">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt necessitatibus perspiciatis corporis neque sequi veniam ex unde? Quis eum quos tenetur harum omnis pariatur eius non. Corrupti vel asperiores animi!
                    </div>
                    <div class="comment-status">
                    <button class="button-delete ">Xóa comment</button>
                    <div class="a">
                    <div class="buttonlikecontainer"><button class="like-btn">1 Likes</button></div>
                    
                    </div>
                    </div>
                    </div>
                    
                </div>
                
                
                
            </div>
            </div>
            
            
        </div>
        
    </div>
</div>