<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Đăng nhập </h2>
  

    <!-- Icon -->
    

    <!-- Login Form -->
    <form method="post">
      <input type="text" name="username"  class="form-control" id="username"  placeholder="Enter email">
      <input type="password"  class="fadeIn third" name="password" placeholder="password">

      <input type="submit" class=" fadeIn fourth"  value="Đăng nhập">
      <input type="hidden" name="action" value="login1" >
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>