<div class="container-fluid">
    <div class="page-header">
        <h3 class="title-header">Bài viết trong forum</h3>
        <button type="button" class="btn button-tag btn-primary filter-button">
            Sắp xếp <span class="badge badge-light">+</span>
        </button>
    </div>

    <div class="wrapper">
        <div class="card post-card">
            <div class="card-header">
            <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
            <span>Nguyen Minh Quang</span>
            <button type="button" class="btn btn-danger ban-button">Xóa bài viết</button>
            </div>
            <div class="card-body body-post">
                <div class="answer"> 
                <p class="card-text">Answer</p>
                <p class="card-text">123</p>
                </div>
                <div class="post-detail"> 
                <p class="title-text">Lorem ipsum dolor sit amet consectetur adipisicing elit ?</p>
                <button type="button" class="btn btn-primary btn-sm">CSS</button>
                <button type="button" class="btn btn-primary btn-sm">HTML</button>
                <button type="button" class="btn btn-primary btn-sm">PHP</button>
            </div>
            
            </div>
            <div class="card-footer button-browse ">
                <a href="index.php?action=detail&&id=1"><button type="button" class="btn btn-primary ahr">Xem chi tiết</button></a>
                
            </div>
            
        </div>
        <div class="card post-card">
            <div class="card-header">
            <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
            <span>Nguyen Minh Quang</span>
            <button type="button" class="btn btn-danger ban-button">Xóa bài viết</button>
            </div>
            <div class="card-body body-post">
                <div class="answer"> 
                <p class="card-text">Answer</p>
                <p class="card-text">123</p>
                </div>
                <div class="post-detail"> 
                <p class="title-text">Lorem ipsum dolor sit amet consectetur adipisicing elit ?</p>
                <button type="button" class="btn btn-primary btn-sm">CSS</button>
                <button type="button" class="btn btn-primary btn-sm">HTML</button>
                <button type="button" class="btn btn-primary btn-sm">PHP</button>
            </div>
            
            </div>
            <div class="card-footer button-browse ">
                <button type="button" class="btn btn-primary">Xem chi tiết</button>
                
            </div>
            
        </div>
    </div>
</div>