<?php $rank = 1; ?>
<?php $color = "yellow"; ?>
<div class="container-fluid">
    <div class="page-header">
        <h3 class="title-header">Bảng xếp hạng</h3>

    </div>
    <?php

    foreach ($ranking as $item => $value) {


    ?>



        <div class="row ranking" style="padding-bottom:20px">

            <div class="col-md-1">
                <?php
                if ($rank == 1) {
                    $color = "yellow";
                } elseif ($rank == 2) {
                    $color = "grey";
                } elseif ($rank == 3) {
                    $color = "#8B4513";
                }
                else {
                    $color = "white";
                }
                ?>
                <i class="fa fa-trophy" style="font-size:48px;color:<?php echo $color ?>"><?php echo $rank ?></i>
               
                
                <?php $rank = $rank + 1 ?>
            </div>
            <div class="col-md-2">
                <div class="profile-img">
                    <img src="/view/img_avatar2.png" alt="Card image cap" />

                </div>
            </div>

            <div class="col-md-2 info ">
                <div class="profile-head">
                    <h5>
                        <?php echo $value["username"] ?>
                    </h5>



                </div>
            </div>
            <div class="col-md-2">
                <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Xem chi tiết" />
            </div>
        </div>
    <?php
    }
    ?>
</div>