<div class="container-fluid">
    <div class="page-header">
        <h3 class="title-header">Bảng xếp hạng</h3>

    </div>
    <div class="row ranking">
        <div class="col-md-1">
            <i class="fa fa-trophy" style="font-size:48px;color:grey">1</i>
        </div>
        <div class="col-md-2">
            <div class="profile-img">
                <img src="/view/img_avatar2.png" alt="Card image cap" />

            </div>
        </div>

        <div class="col-md-2 info ">
            <div class="profile-head">
                <h5>
                    asdasdas
                </h5>



            </div>
        </div>
        <div class="col-md-2">
                <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Xem chi tiết" />
        </div>
    </div>
</div>