<div class="container-fluid">
    <div class="page-header">
        <h3 class="title-header">Các tag hiện có</h3>
        <button type="button" class="btn button-tag btn-primary">
            Tạo Tag <span class="badge badge-light">+</span>
        </button>
    </div>
    <div class="table-wrapper">
              <table class="table">
                    <thead>
                        <tr class="table-primary">
                            <th scope="col">#</th>
                            <th scope="col">Tag</th>
                            <th scope="col">Mô tả</th>
                            <th scope="col">Câu hỏi</th>
                            <th scope="col">Trả lời</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th style="width: 10%;" scope="row">1</th>
                            <td style="width: 10%;">CSS</td>
                            <td style="width: 50%;">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium alias aut adipisci earum asperiores aliquam nemo ullam perferendis? Earum placeat magnam, quasi et aspernatur nulla vitae deleniti quam recusandae. Velit?</td>
                            <td style="width: 10%;">127</td>
                            <td style="width: 10%;">43</td>
                            <td><button type="button" class="btn btn-outline-secondary">Xem</button></td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Jacob</td>
                            <td>Thornton</td>
                            <td>@fat</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Larry</td>
                            <td>the Bird</td>
                            <td>@twitter</td>
                        </tr>
                    </tbody>
                </table>
     
            <!-- <div class="row">
        <div class=" tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <button href="#" class="btn btn-primary stretched-link">CSS</button>
                <p class="card-text tag-description">Some example text some example text. John Doe is an architect and engineer</p>
                
            </div>
            <div class="card-footer bg-transparent ">126 Question,28 Answer</div>
        </div>
        </div>
        <div class="tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <h4 class="card-title">John Doe</h4>
                <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                <a href="#" class="btn btn-primary stretched-link">See Profile</a>
            </div>
            </div>
        </div>
        <div class="tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <h4 class="card-title">John Doe</h4>
                <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                <a href="#" class="btn btn-primary stretched-link">See Profile</a>
            </div>
            </div>
        </div>
        <div class="tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <h4 class="card-title">John Doe</h4>
                <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                <a href="#" class="btn btn-primary stretched-link">See Profile</a>
            </div>
            </div>
        </div>
        <div class="tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <h4 class="card-title">John Doe</h4>
                <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                <a href="#" class="btn btn-primary stretched-link">See Profile</a>
            </div>
            </div>
        </div>
    </div> -->
        
    </div>
    <!-- <div class="row">
        <div class=" tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <button href="#" class="btn btn-primary stretched-link">CSS</button>
                <p class="card-text tag-description">Some example text some example text. John Doe is an architect and engineer</p>
                
            </div>
            <div class="card-footer bg-transparent ">126 Question,28 Answer</div>
        </div>
        </div>
        <div class="tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <h4 class="card-title">John Doe</h4>
                <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                <a href="#" class="btn btn-primary stretched-link">See Profile</a>
            </div>
            </div>
        </div>
        <div class="tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <h4 class="card-title">John Doe</h4>
                <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                <a href="#" class="btn btn-primary stretched-link">See Profile</a>
            </div>
            </div>
        </div>
        <div class="tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <h4 class="card-title">John Doe</h4>
                <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                <a href="#" class="btn btn-primary stretched-link">See Profile</a>
            </div>
            </div>
        </div>
        <div class="tag col-lg-3">
            <div class="card" style="width:300px;height:300px ">
            <div class="card-body">
                <h4 class="card-title">John Doe</h4>
                <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                <a href="#" class="btn btn-primary stretched-link">See Profile</a>
            </div>
            </div>
        </div>
    </div> -->
</div>