<div class="container-fluid user-page">
    <div class="page-header">
        <h4 class="title-header">Người dùng hiện có</h4>
        <div class="dropdown">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Sắp xếp
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Cũ nhất</a>
                <a class="dropdown-item" href="#">Mới nhất</a>

            </div>
        </div>
    </div>

    <div class="wrapper">
        <p class="user-header">
            <b>Số lượng người dùng: </b><span style="color:#B0B0B0;font-weight:600">10</span>
        </p>
        <div class="container">
    <div class="row height d-flex justify-content-center align-items-center">
        <div class="col-md-8">
            <div class="search"> <i class="fa fa-search"></i> <input type="text" class="form-control" placeholder="Tìm thành viên"></div>
        </div>
    </div>
    <div class="line"></div>
</div>

        <div class="user-wrapper">
            <div class="card user-info">

                <div class="card-body">
                    <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                    <span>Nguyen Minh Quang</span>
                    <p class="text-post">
                        <span>0 Vi phạm, </span>
                        <span>3 Bài viết, </span>
                        <span>1 Trả lời, </span>
                    </p>
                </div>
                <div class="card-footer button-browse ">
                    <button type="button" class="btn btn-danger">Chặn người dùng</button>
                    <button type="button" class="btn btn-primary">Xem thông tin</button>


                </div>
            </div>
            <div class="card user-info">

                <div class="card-body">
                    <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                    <span>Nguyen Minh Quang</span>
                    <p class="text-post">
                        <span>0 Vi phạm, </span>
                        <span>3 Bài viết, </span>
                        <span>1 Trả lời, </span>
                    </p>
                </div>
                <div class="card-footer button-browse ">
                    <button type="button" class="btn btn-danger">Chặn người dùng</button>
                    <button type="button" class="btn btn-primary">Xem thông tin</button>


                </div>
            </div>

        </div>

        <ul class="pagination">
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active" aria-current="page">
                <span class="page-link">2</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </div>
</div>