<div class="container-fluid user-page">
    <div class="page-header">
        <h4 class="title-header">Người dùng hiện có</h4>
        <div class="dropdown">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Sắp xếp
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Cũ nhất</a>
                <a class="dropdown-item" href="#">Mới nhất</a>

            </div>
        </div>
    </div>

    <div class="wrapper">
        <p class="user-header">
            <b>Số lượng người dùng: </b><span style="color:#B0B0B0;font-weight:600"><?php echo count($data) ?></span>
        </p>
        <div class="container">
            <div class="row height d-flex justify-content-center align-items-center">
                <div class="col-md-8">
                    <div class="search"> <i class="fa fa-search"></i> <input type="text" class="form-control" placeholder="Tìm thành viên"></div>
                </div>
            </div>
            <div class="line"></div>
        </div>

        <div class="user-wrapper">
            <?php
            foreach ($data as $item =>$value) 
            {
            ?>
                <div class="card user-info">

                    <div class="card-body">
                        <img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap">
                        <span><?php echo $value["first_name"] ?> <?php echo $value["last_name"] ?></span>
                        <p class="text-post">
                            <span>0 Vi phạm, </span>
                            <span>3 Bài viết, </span>
                            <span><?php echo $value["numOfComments"] ?> Trả lời, </span>
                        </p>
                    </div>
                    <div class="card-footer button-browse ">
                        <form>
                        <button type="submit" class="btn btn-danger" name="action" value="delete-user" >Chặn người dùng</button>
                        <input type="hidden" name="userid" value=<?php echo $value["user_id"]; ?> />
                        </form>
                        <form action="index.php?action=detail-user">
                        <button type="submit" class="btn btn-primary" name="action" value="detail-user" >Xem thông tin</button>
                        
                        <input type="hidden" name="userid" value=<?php echo $value["user_id"]; ?> />
                        <input type="hidden" name="firstname" value=<?php echo $value["first_name"]; ?> />
                        <input type="hidden" name="lastname" value=<?php echo $value["last_name"]; ?> />
                        <input type="hidden" name="email" value=<?php echo $value["email"]; ?> />
                        <input type="hidden" name="username" value=<?php echo $value["username"] ?> />
                        </form>

                    </div>
                </div>
            <?php
            } 
            ?>



        </div>

        <ul class="pagination">
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active" aria-current="page">
                <span class="page-link">2</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </div>
</div>