<!DOCTYPE html>
<html>

<head>
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="../../css/bootstrap.min.css" type="text/css" rel="stylesheet">
  
 
  <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
  <link rel="stylesheet" type="text/css" href="../css/style.css" />
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>

<body>

  <div class="page-wrapper chiller-theme toggled">
    <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
      <i class="fas fa-bars"></i>
    </a>
    <nav id="sidebar" class="sidebar-wrapper ">
  <div class="sidebar-content">
    <div class="sidebar-brand">
      <a href="#">Quản lý</a>
      <div id="close-sidebar">
        <i class="fas fa-times"></i>
      </div>
    </div>

    <div class="sidebar-menu">
      <ul>
        <li class="sidebar-dropdown">
          <a href="index.php?action=user">
            <i class="fa fa-tachometer-alt"></i>
            <span>Người dùng hiện có</span>
          </a>

        </li>
        <li class="sidebar-dropdown">
          <a href="index.php?action=tag-list">
            <i class="fa fa-shopping-cart"></i>
            <span>Tags</span>

          </a>
          <div class="sidebar-submenu">
            <ul>
              <li>
                <a href="#">Products

                </a>
              </li>
              <li>
                <a href="#">Orders</a>
              </li>
              <li>
                <a href="#">Credit cart</a>
              </li>
            </ul>
          </div>
        </li>
        <li class="sidebar-dropdown">
          <a href="index.php?action=accept-post">
            <i class="far fa-gem"></i>
            <span>Duyệt câu hỏi</span>
          </a>
          <div class="sidebar-submenu">
            <ul>
              <li>
                <a href="#">General</a>
              </li>
              <li>
                <a href="#">Panels</a>
              </li>
              <li>
                <a href="#">Tables</a>
              </li>
              <li>
                <a href="#">Icons</a>
              </li>
              <li>
                <a href="#">Forms</a>
              </li>
            </ul>
          </div>
        </li>
        <li class="sidebar-dropdown">
          <a href="index.php?action=post">
            <i class="fa fa-chart-line"></i>
            <span>Các câu hỏi hiện có</span>
          </a>
          <div class="sidebar-submenu">
            <ul>
              <li>
                <a href="#">Pie chart</a>
              </li>
              <li>
                <a href="#">Line chart</a>
              </li>
              <li>
                <a href="#">Bar chart</a>
              </li>
              <li>
                <a href="#">Histogram</a>
              </li>
            </ul>
          </div>
        </li>
      </ul>


    </div>
    <!-- sidebar-menu  -->
  </div>
  <!-- sidebar-content  -->
  <div class="sidebar-footer">
    <a href="#">
      <i class="fa fa-bell"></i>
      <span class="badge badge-pill badge-warning notification">3</span>
    </a>
    <a href="#">
      <i class="fa fa-envelope"></i>
      <span class="badge badge-pill badge-success notification">7</span>
    </a>
    <a href="#">
      <i class="fa fa-cog"></i>
      <span class="badge-sonar"></span>
    </a>
    <a href="#">
      <i class="fa fa-power-off"></i>
    </a>
  </div>
</nav>
<div class="nav-header" style="width: 100%">
<img class="card-img-top avatar" src="/view/img_avatar2.png" alt="Card image cap"></img>
</div>
    <!-- sidebar-wrapper  -->
    <main class="page-content">
    
      <div id="primary">
        <?php require($VIEW); ?>
      </div>
    </main>
    <!-- page-content" -->

  </div>

</body>

</html>
